version: '3.8'

services:
  app:
    build: .
    restart: always
    container_name: spring_sort
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge